---
title: "Div Sup Analysis"
output: html_document
date: "2024-04-29"
---

```{r, include = F}
library(tidyverse)
library(broom)
library(here)
library(scales)
library(kableExtra)
library(oddsratio)
library(modelsummary)
`%+%` <- paste0

clean_data <- readRDS(here("Clean Data.rds"))
barrier_data <- readRDS(here("Barrier Data.rds"))

# Functions
# CI's using Wilson's score method (see Newcombe 1998)
prop_ci <- Vectorize(function(x, n, side = c("lower", "upper")) {
  
  test_output <- prop.test(x = x, n = n)
  
  if(side == "lower") {
    
    return(test_output$conf.int[1])
    
  } else if(side == "upper") {
    
    return(test_output$conf.int[2])
    
  }
  
})

my_figure <- function(x, y) {
  
  plot_data <- clean_data %>%
    drop_na({{x}}, {{y}}) %>%
    group_by({{x}}) %>%
    summarize(
      x = sum({{y}}),
      n = n()
    ) %>%
    mutate(
      mean = x / n,
      lower = prop_ci(x, n, "lower"),
      upper = prop_ci(x, n, "upper")
    )
  
  print(plot_data)
  
  plot <- plot_data %>%
    ggplot(aes({{x}}, mean)) +
    geom_col() +
    geom_errorbar(aes(ymin = lower, ymax = upper), width = .5) +
    scale_y_continuous(name = substitute(y), limits = c(0, 1), labels = percent) +
    theme_classic()

  return(plot)
  
}

my_model <- function(formula, incr) {
  
  model_output <- glm(
    data = clean_data,
    formula,
    family = "binomial"
  )

  odds_ratios <- or_glm(clean_data, model_output, incr = incr)

  p_values <- model_output %>%
    tidy() %>%
    select(predictor = term, p.value)
  
  out <- left_join(odds_ratios, p_values, by = "predictor")
  
  out %>%
    kable(digits = 3) %>%
    kable_styling() %>%
    return()
  
}
```

## Descriptive Statistics

```{r}

```

## Uptake by Researcher Characteristics

```{r, results = "asis"}
predictors <- c(
  "age",
  "gender",
  "race_ethnicity",
  "discipline",
  "institution_type",
  "job_title",
  "research_time",
  "research_funding",
  "years_experience",
  "mentor_undergrad",
  "mentor_postgrad",
  "mentor_masters",
  "mentor_doctoral",
  "mentor_postdoc",
  "mentor_ecr"
)

models <- list()

for(x in predictors) {
  
  models[[x]] <- glm(
    data = clean_data,
    formula = as.formula("div_sup_applied ~ " %+% x),
    family = "binomial"
  )
  
}

models[["combined"]] <- glm(
  data = clean_data,
  formula = as.formula("div_sup_applied ~ " %+% paste(predictors, collapse = " + ")),
  family = "binomial"
)

# Currently, no p-value adjustment. To do this in the modelsummary workflow,
# export type = "modelsummary_list" and modify the p-values there before passing
# the revised outputs back to modelsummary
modelsummary(
  models, 
  exponentiate = T, 
  estimate = "{estimate}{stars}",
  statistic = "[{conf.low} {conf.high}]"
)
```

## Barriers

```{r}
barrier_summary_data <- barrier_data %>%
  pivot_longer(c(barriers, top_barrier)) %>%
  mutate(
    n = n_distinct(response_id),
    name = recode(
      name, 
      "barriers" = "Any Barrier",
      "top_barrier" = "Top Barrier"
    )
  ) %>%
  drop_na() %>%
  group_by(name, value) %>%
  summarize(
    x = n(),
    n = mean(n),
    .groups = "drop"
  ) %>%
  mutate(
    value = fct_reorder(value, x),
    prop = x / n,
    lower = prop_ci(x, n, "lower"),
    upper = prop_ci(x, n, "upper")
  )

barrier_summary_data %>%
  mutate(
    across(
      c(prop, lower, upper),
      ~ percent(., 1)
    )
  ) %>%
  kable() %>%
  kable_styling()

barrier_summary_data %>%
  ggplot(aes(value, prop, group = name, fill = name)) +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = lower, ymax = upper), position = position_dodge(width = .9), width = .5) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = NULL, labels = percent) +
  scale_fill_discrete(name = NULL) +
  coord_flip() +
  theme_classic()
```
